name: "Java Maven ECS"

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: app/Dockerfile

  ci-java-maven:
    uses: kumabes-org/reusable-workflows-ci-java-maven/.github/workflows/ci.yml@main
    with:
      runs-on: "ubuntu-latest"
      environment: "production"
      working-directory: "app"
      shell: "bash"
      project-name: "insurance-catalog"
      java-distribution: "zulu"
      java-version: "21"
      maven-version: "3.9.6"
    secrets: inherit

  package:
    needs: [lint, ci-java-maven]
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - uses: actions/download-artifact@v8.0.1
        with:
          name: "insurance-catalog-build"
          path: "./app/target"

      - name: Display structure of downloaded files
        run: |
          pwd
          ls -R
          cd app
          pwd
          docker build . -t "${IMAGE_NAME}:${VERSION_ARG}"
          docker image ls
          docker save -o ${IMAGE_TAR} "${IMAGE_NAME}${VERSION_ARG}"
        env:
          IMAGE_NAME: "insurance-catalog"
          VERSION_ARG: "latest"
          IMAGE_TAR: "insurance-catalog.tar"  

  inspection:
    needs: [lint, ci-java-maven]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

  publish:
    needs: [package, inspection]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2