name: "Java Maven ECS"

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: app/Dockerfile

  ci-java-maven:
    uses: kumabes-org/reusable-workflows-ci-java-maven/.github/workflows/ci.yml@main
    with:
      runs-on: "ubuntu-latest"
      environment: "production"
      working-directory: "app"
      shell: "bash"
      project-name: "insurance-catalog"
      java-distribution: "zulu"
      java-version: "21"
      maven-version: "3.9.6"
    secrets: inherit

  package:
    needs: [lint, ci-java-maven]
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - uses: actions/download-artifact@v8.0.1
        with:
          name: "insurance-catalog-build"
          path: "./app/target"

      - name: Display structure of downloaded files
        run: |
          pwd
          ls -R
          cd app
          pwd
          docker build . -t "${IMAGE_NAME}:${VERSION_ARG}"
          docker image ls
          docker save -o ${IMAGE_TAR} "${IMAGE_NAME}:${VERSION_ARG}"
          ls -lrth --color
        env:
          IMAGE_NAME: "insurance-catalog"
          VERSION_ARG: "latest"
          IMAGE_TAR: "insurance-catalog.tar"

      - uses: actions/upload-artifact@v4
        with:
          name: "${{ env.IMAGE_NAME }}-package"
          retention-days: 1
          path: |
            ${{ github.workspace }}/app/${{ env.IMAGE_TAR }}
        env:
          IMAGE_NAME: "insurance-catalog"
          VERSION_ARG: "latest"
          IMAGE_TAR: "insurance-catalog.tar"
  inspection:
    needs: [lint, ci-java-maven]
    uses: kumabes-org/reusable-workflows-codeql/.github/workflows/main.yml@main
    with:
      runs-on: "ubuntu-latest"
      environment: "production"
      working-directory: "app"
      shell: "bash"
      project-name: "insurance-catalog"
      languages: "java"
    secrets: inherit


  publish:
    needs: [package, inspection]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/download-artifact@v8.0.1
        with:
          name: "insurance-catalog-package"
          path: "./app"
      - name: Prepare for publishing
        run: |        
          pwd
          ls -lrth --color
          cd app
          pwd
          ls -lrth --color
          docker image ls
          docker load -i ${IMAGE_TAR}
          docker image ls          
        env:
          IMAGE_NAME: "insurance-catalog"
          VERSION_ARG: "latest"
          IMAGE_TAR: "insurance-catalog.tar"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'image'
          image-ref: '${{ env.IMAGE_NAME }}:${{ env.VERSION_ARG }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
        env:
          IMAGE_NAME: "insurance-catalog"
          VERSION_ARG: "latest"
          ORGANIZATION: "rotoku"

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./app
          push: true
          tags: |            
            ${{ env.ORGANIZATION }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.ORGANIZATION }}/${{ env.IMAGE_NAME }}:${{ env.VERSION_ARG }}
        env:
          IMAGE_NAME: "insurance-catalog"
          VERSION_ARG: "latest"
          ORGANIZATION: "rotoku"