name: "Java Maven ECS"

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: app/Dockerfile

  ci-java-maven:
    uses: kumabes-org/reusable-workflows-ci-java-maven/.github/workflows/ci.yml@main
    with:
      runs-on: "ubuntu-latest"
      environment: "production"
      working-directory: "app"
      shell: "bash"
      project-name: "insurance-catalog"
      java-distribution: "zulu"
      java-version: "21"
      maven-version: "3.9.6"
    secrets: inherit

  package:
    needs: [lint, ci-java-maven]
    
    runs-on: ubuntu-latest
    steps:
      - name: package application
        run: echo "Packaging application..."

  inspection:
    needs: [lint, ci-java-maven]
    runs-on: ubuntu-latest
    steps:
      - name: inspection code
        run: echo "Running code inspection..."

  publish:
    needs: [package, inspection]
    runs-on: ubuntu-latest
    steps:
      - name: publish application
        run: echo "Publishing to repository..."